--
-- PostgreSQL database dump
--

-- Dumped from database version 16.9 (Debian 16.9-1.pgdg120+1)
-- Dumped by pg_dump version 16.9 (Debian 16.9-1.pgdg120+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: auth; Type: SCHEMA; Schema: -; Owner: -
--

CREATE SCHEMA auth;


--
-- Name: client; Type: SCHEMA; Schema: -; Owner: -
--

CREATE SCHEMA client;


--
-- Name: depot; Type: SCHEMA; Schema: -; Owner: -
--

CREATE SCHEMA depot;


--
-- Name: shipping; Type: SCHEMA; Schema: -; Owner: -
--

CREATE SCHEMA shipping;


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: revoked_token; Type: TABLE; Schema: auth; Owner: -
--

CREATE TABLE auth.revoked_token (
    id bigint NOT NULL,
    revoked_at timestamp(6) without time zone NOT NULL,
    token_hash character varying(64) NOT NULL
);


--
-- Name: revoked_token_id_seq; Type: SEQUENCE; Schema: auth; Owner: -
--

ALTER TABLE auth.revoked_token ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME auth.revoked_token_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: session; Type: TABLE; Schema: auth; Owner: -
--

CREATE TABLE auth.session (
    is_active boolean NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    expires_at timestamp(6) without time zone NOT NULL,
    id bigint NOT NULL,
    last_activity_at timestamp(6) without time zone NOT NULL,
    user_id bigint NOT NULL,
    ip_address character varying(45),
    access_token_hash character varying(64) NOT NULL,
    refresh_token_hash character varying(64) NOT NULL,
    user_agent character varying(1024)
);


--
-- Name: session_id_seq; Type: SEQUENCE; Schema: auth; Owner: -
--

ALTER TABLE auth.session ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME auth.session_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tempo_role; Type: TABLE; Schema: auth; Owner: -
--

CREATE TABLE auth.tempo_role (
    id bigint NOT NULL,
    name character varying(50) NOT NULL
);


--
-- Name: tempo_role_id_seq; Type: SEQUENCE; Schema: auth; Owner: -
--

ALTER TABLE auth.tempo_role ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME auth.tempo_role_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tempo_role_user; Type: TABLE; Schema: auth; Owner: -
--

CREATE TABLE auth.tempo_role_user (
    id bigint NOT NULL,
    role_id bigint NOT NULL,
    user_id bigint NOT NULL
);


--
-- Name: tempo_role_user_id_seq; Type: SEQUENCE; Schema: auth; Owner: -
--

ALTER TABLE auth.tempo_role_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME auth.tempo_role_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tempo_user; Type: TABLE; Schema: auth; Owner: -
--

CREATE TABLE auth.tempo_user (
    account_non_locked boolean NOT NULL,
    email_confirmed boolean NOT NULL,
    enabled boolean NOT NULL,
    login_attempts integer,
    client_id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    id bigint NOT NULL,
    last_activity_at timestamp(6) without time zone,
    last_login_at timestamp(6) without time zone,
    recuperation_token_exp_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone NOT NULL,
    recuperation_token character varying(10),
    username character varying(20) NOT NULL,
    password_hash character varying(150) NOT NULL,
    email character varying(255) NOT NULL
);


--
-- Name: tempo_user_id_seq; Type: SEQUENCE; Schema: auth; Owner: -
--

ALTER TABLE auth.tempo_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME auth.tempo_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: business; Type: TABLE; Schema: client; Owner: -
--

CREATE TABLE client.business (
    client_id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    name_code character varying(18) NOT NULL,
    ruc_number character varying(50) NOT NULL,
    name character varying(100) NOT NULL,
    contact_name character varying(255) NOT NULL
);


--
-- Name: client; Type: TABLE; Schema: client; Owner: -
--

CREATE TABLE client.client (
    po_box_number integer NOT NULL,
    terms_version character varying(5),
    created_at timestamp(6) without time zone NOT NULL,
    id bigint NOT NULL,
    referred_by_client_id bigint,
    terms_accepted_at timestamp(6) without time zone,
    type_id bigint NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    phone_number_pri character varying(20) NOT NULL,
    phone_number_sec character varying(20)
);


--
-- Name: client_id_seq; Type: SEQUENCE; Schema: client; Owner: -
--

ALTER TABLE client.client ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME client.client_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: client_type; Type: TABLE; Schema: client; Owner: -
--

CREATE TABLE client.client_type (
    code character varying(4) NOT NULL,
    id bigint NOT NULL,
    display_name character varying(20) NOT NULL
);


--
-- Name: client_type_id_seq; Type: SEQUENCE; Schema: client; Owner: -
--

ALTER TABLE client.client_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME client.client_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: delivery_address; Type: TABLE; Schema: client; Owner: -
--

CREATE TABLE client.delivery_address (
    country character varying(2) NOT NULL,
    is_default boolean NOT NULL,
    client_id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    id bigint NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    province character varying(25) NOT NULL,
    address_name character varying(30) NOT NULL,
    district character varying(50) NOT NULL,
    corregimiento character varying(100) NOT NULL,
    address character varying(300) NOT NULL
);


--
-- Name: delivery_address_id_seq; Type: SEQUENCE; Schema: client; Owner: -
--

ALTER TABLE client.delivery_address ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME client.delivery_address_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: identity_type; Type: TABLE; Schema: client; Owner: -
--

CREATE TABLE client.identity_type (
    code character varying(4) NOT NULL,
    id bigint NOT NULL,
    display_name character varying(20) NOT NULL
);


--
-- Name: identity_type_id_seq; Type: SEQUENCE; Schema: client; Owner: -
--

ALTER TABLE client.identity_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME client.identity_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: individual; Type: TABLE; Schema: client; Owner: -
--

CREATE TABLE client.individual (
    client_id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    date_of_birth timestamp(6) without time zone NOT NULL,
    identity_type_id bigint NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    name_code character varying(18) NOT NULL,
    identity_number character varying(20) NOT NULL,
    first_name character varying(255) NOT NULL,
    last_name character varying(255) NOT NULL
);


--
-- Name: warehouse_address; Type: TABLE; Schema: depot; Owner: -
--

CREATE TABLE depot.warehouse_address (
    is_active boolean NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    id bigint NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    warehouse_type_id bigint NOT NULL,
    warehouse_name character varying(25) NOT NULL
);


--
-- Name: warehouse_address_id_seq; Type: SEQUENCE; Schema: depot; Owner: -
--

ALTER TABLE depot.warehouse_address ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME depot.warehouse_address_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: warehouse_cn; Type: TABLE; Schema: depot; Owner: -
--

CREATE TABLE depot.warehouse_cn (
    warehouse_address_id bigint NOT NULL,
    phone_number character varying(20),
    full_address_cn text NOT NULL
);


--
-- Name: warehouse_co; Type: TABLE; Schema: depot; Owner: -
--

CREATE TABLE depot.warehouse_co (
    country_code character varying(2) NOT NULL,
    postal_code character varying(6) NOT NULL,
    warehouse_address_id bigint NOT NULL,
    phone_number character varying(20),
    department character varying(30) NOT NULL,
    city character varying(50) NOT NULL,
    barrio character varying(100) NOT NULL,
    street_line character varying(300) NOT NULL
);


--
-- Name: warehouse_type; Type: TABLE; Schema: depot; Owner: -
--

CREATE TABLE depot.warehouse_type (
    code character varying(2) NOT NULL,
    id bigint NOT NULL,
    display_name character varying(20) NOT NULL
);


--
-- Name: warehouse_type_id_seq; Type: SEQUENCE; Schema: depot; Owner: -
--

ALTER TABLE depot.warehouse_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME depot.warehouse_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: warehouse_us; Type: TABLE; Schema: depot; Owner: -
--

CREATE TABLE depot.warehouse_us (
    country_code character varying(2) NOT NULL,
    warehouse_address_id bigint NOT NULL,
    phone_number character varying(15),
    postal_code character varying(20) NOT NULL,
    state_province character varying(50) NOT NULL,
    city character varying(85) NOT NULL,
    street_line_2 character varying(100),
    street_line_1 character varying(200) NOT NULL
);


--
-- Name: package_status; Type: TABLE; Schema: shipping; Owner: -
--

CREATE TABLE shipping.package_status (
    code character varying(4) NOT NULL,
    id bigint NOT NULL,
    display_name character varying(20) NOT NULL
);


--
-- Name: package_status_id_seq; Type: SEQUENCE; Schema: shipping; Owner: -
--

ALTER TABLE shipping.package_status ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME shipping.package_status_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tempo_package; Type: TABLE; Schema: shipping; Owner: -
--

CREATE TABLE shipping.tempo_package (
    client_id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    delivery_address_id bigint,
    id bigint NOT NULL,
    package_status_id bigint NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    warehouse_address_id bigint NOT NULL,
    tracking_number character varying(30) NOT NULL
);


--
-- Name: tempo_package_id_seq; Type: SEQUENCE; Schema: shipping; Owner: -
--

ALTER TABLE shipping.tempo_package ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME shipping.tempo_package_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: revoked_token revoked_token_pkey; Type: CONSTRAINT; Schema: auth; Owner: -
--

ALTER TABLE ONLY auth.revoked_token
    ADD CONSTRAINT revoked_token_pkey PRIMARY KEY (id);


--
-- Name: revoked_token revoked_token_token_hash_key; Type: CONSTRAINT; Schema: auth; Owner: -
--

ALTER TABLE ONLY auth.revoked_token
    ADD CONSTRAINT revoked_token_token_hash_key UNIQUE (token_hash);


--
-- Name: tempo_role role_name_unique; Type: CONSTRAINT; Schema: auth; Owner: -
--

ALTER TABLE ONLY auth.tempo_role
    ADD CONSTRAINT role_name_unique UNIQUE (name);


--
-- Name: tempo_role_user role_user_roleid_userid_unique; Type: CONSTRAINT; Schema: auth; Owner: -
--

ALTER TABLE ONLY auth.tempo_role_user
    ADD CONSTRAINT role_user_roleid_userid_unique UNIQUE (role_id, user_id);


--
-- Name: session session_access_token_hash_key; Type: CONSTRAINT; Schema: auth; Owner: -
--

ALTER TABLE ONLY auth.session
    ADD CONSTRAINT session_access_token_hash_key UNIQUE (access_token_hash);


--
-- Name: session session_pkey; Type: CONSTRAINT; Schema: auth; Owner: -
--

ALTER TABLE ONLY auth.session
    ADD CONSTRAINT session_pkey PRIMARY KEY (id);


--
-- Name: session session_refresh_token_hash_key; Type: CONSTRAINT; Schema: auth; Owner: -
--

ALTER TABLE ONLY auth.session
    ADD CONSTRAINT session_refresh_token_hash_key UNIQUE (refresh_token_hash);


--
-- Name: tempo_role tempo_role_pkey; Type: CONSTRAINT; Schema: auth; Owner: -
--

ALTER TABLE ONLY auth.tempo_role
    ADD CONSTRAINT tempo_role_pkey PRIMARY KEY (id);


--
-- Name: tempo_role_user tempo_role_user_pkey; Type: CONSTRAINT; Schema: auth; Owner: -
--

ALTER TABLE ONLY auth.tempo_role_user
    ADD CONSTRAINT tempo_role_user_pkey PRIMARY KEY (id);


--
-- Name: tempo_user tempo_user_client_id_key; Type: CONSTRAINT; Schema: auth; Owner: -
--

ALTER TABLE ONLY auth.tempo_user
    ADD CONSTRAINT tempo_user_client_id_key UNIQUE (client_id);


--
-- Name: tempo_user tempo_user_pkey; Type: CONSTRAINT; Schema: auth; Owner: -
--

ALTER TABLE ONLY auth.tempo_user
    ADD CONSTRAINT tempo_user_pkey PRIMARY KEY (id);


--
-- Name: tempo_user user_email_unique; Type: CONSTRAINT; Schema: auth; Owner: -
--

ALTER TABLE ONLY auth.tempo_user
    ADD CONSTRAINT user_email_unique UNIQUE (email);


--
-- Name: tempo_user user_username_unique; Type: CONSTRAINT; Schema: auth; Owner: -
--

ALTER TABLE ONLY auth.tempo_user
    ADD CONSTRAINT user_username_unique UNIQUE (username);


--
-- Name: business business_name_unique; Type: CONSTRAINT; Schema: client; Owner: -
--

ALTER TABLE ONLY client.business
    ADD CONSTRAINT business_name_unique UNIQUE (name);


--
-- Name: business business_namecode_unique; Type: CONSTRAINT; Schema: client; Owner: -
--

ALTER TABLE ONLY client.business
    ADD CONSTRAINT business_namecode_unique UNIQUE (name_code);


--
-- Name: business business_pkey; Type: CONSTRAINT; Schema: client; Owner: -
--

ALTER TABLE ONLY client.business
    ADD CONSTRAINT business_pkey PRIMARY KEY (client_id);


--
-- Name: business business_rucnumber_unique; Type: CONSTRAINT; Schema: client; Owner: -
--

ALTER TABLE ONLY client.business
    ADD CONSTRAINT business_rucnumber_unique UNIQUE (ruc_number);


--
-- Name: client client_pkey; Type: CONSTRAINT; Schema: client; Owner: -
--

ALTER TABLE ONLY client.client
    ADD CONSTRAINT client_pkey PRIMARY KEY (id);


--
-- Name: client client_poboxnumber_unique; Type: CONSTRAINT; Schema: client; Owner: -
--

ALTER TABLE ONLY client.client
    ADD CONSTRAINT client_poboxnumber_unique UNIQUE (po_box_number);


--
-- Name: client_type client_type_code_unique; Type: CONSTRAINT; Schema: client; Owner: -
--

ALTER TABLE ONLY client.client_type
    ADD CONSTRAINT client_type_code_unique UNIQUE (code);


--
-- Name: client_type client_type_displayname_unique; Type: CONSTRAINT; Schema: client; Owner: -
--

ALTER TABLE ONLY client.client_type
    ADD CONSTRAINT client_type_displayname_unique UNIQUE (display_name);


--
-- Name: client_type client_type_pkey; Type: CONSTRAINT; Schema: client; Owner: -
--

ALTER TABLE ONLY client.client_type
    ADD CONSTRAINT client_type_pkey PRIMARY KEY (id);


--
-- Name: delivery_address delivery_address_clientid_addressname_unique; Type: CONSTRAINT; Schema: client; Owner: -
--

ALTER TABLE ONLY client.delivery_address
    ADD CONSTRAINT delivery_address_clientid_addressname_unique UNIQUE (client_id, address_name);


--
-- Name: delivery_address delivery_address_pkey; Type: CONSTRAINT; Schema: client; Owner: -
--

ALTER TABLE ONLY client.delivery_address
    ADD CONSTRAINT delivery_address_pkey PRIMARY KEY (id);


--
-- Name: identity_type identity_type_code_unique; Type: CONSTRAINT; Schema: client; Owner: -
--

ALTER TABLE ONLY client.identity_type
    ADD CONSTRAINT identity_type_code_unique UNIQUE (code);


--
-- Name: identity_type identity_type_displayname_unique; Type: CONSTRAINT; Schema: client; Owner: -
--

ALTER TABLE ONLY client.identity_type
    ADD CONSTRAINT identity_type_displayname_unique UNIQUE (display_name);


--
-- Name: identity_type identity_type_pkey; Type: CONSTRAINT; Schema: client; Owner: -
--

ALTER TABLE ONLY client.identity_type
    ADD CONSTRAINT identity_type_pkey PRIMARY KEY (id);


--
-- Name: individual individual_identitynumber_unique; Type: CONSTRAINT; Schema: client; Owner: -
--

ALTER TABLE ONLY client.individual
    ADD CONSTRAINT individual_identitynumber_unique UNIQUE (identity_number);


--
-- Name: individual individual_namecode_unique; Type: CONSTRAINT; Schema: client; Owner: -
--

ALTER TABLE ONLY client.individual
    ADD CONSTRAINT individual_namecode_unique UNIQUE (name_code);


--
-- Name: individual individual_pkey; Type: CONSTRAINT; Schema: client; Owner: -
--

ALTER TABLE ONLY client.individual
    ADD CONSTRAINT individual_pkey PRIMARY KEY (client_id);


--
-- Name: warehouse_address warehouse_address_pkey; Type: CONSTRAINT; Schema: depot; Owner: -
--

ALTER TABLE ONLY depot.warehouse_address
    ADD CONSTRAINT warehouse_address_pkey PRIMARY KEY (id);


--
-- Name: warehouse_address warehouse_address_warehousename_unique; Type: CONSTRAINT; Schema: depot; Owner: -
--

ALTER TABLE ONLY depot.warehouse_address
    ADD CONSTRAINT warehouse_address_warehousename_unique UNIQUE (warehouse_name);


--
-- Name: warehouse_cn warehouse_cn_pkey; Type: CONSTRAINT; Schema: depot; Owner: -
--

ALTER TABLE ONLY depot.warehouse_cn
    ADD CONSTRAINT warehouse_cn_pkey PRIMARY KEY (warehouse_address_id);


--
-- Name: warehouse_co warehouse_co_pkey; Type: CONSTRAINT; Schema: depot; Owner: -
--

ALTER TABLE ONLY depot.warehouse_co
    ADD CONSTRAINT warehouse_co_pkey PRIMARY KEY (warehouse_address_id);


--
-- Name: warehouse_type warehouse_type_code_unique; Type: CONSTRAINT; Schema: depot; Owner: -
--

ALTER TABLE ONLY depot.warehouse_type
    ADD CONSTRAINT warehouse_type_code_unique UNIQUE (code);


--
-- Name: warehouse_type warehouse_type_displayname_unique; Type: CONSTRAINT; Schema: depot; Owner: -
--

ALTER TABLE ONLY depot.warehouse_type
    ADD CONSTRAINT warehouse_type_displayname_unique UNIQUE (display_name);


--
-- Name: warehouse_type warehouse_type_pkey; Type: CONSTRAINT; Schema: depot; Owner: -
--

ALTER TABLE ONLY depot.warehouse_type
    ADD CONSTRAINT warehouse_type_pkey PRIMARY KEY (id);


--
-- Name: warehouse_us warehouse_us_pkey; Type: CONSTRAINT; Schema: depot; Owner: -
--

ALTER TABLE ONLY depot.warehouse_us
    ADD CONSTRAINT warehouse_us_pkey PRIMARY KEY (warehouse_address_id);


--
-- Name: package_status package_status_code_unique; Type: CONSTRAINT; Schema: shipping; Owner: -
--

ALTER TABLE ONLY shipping.package_status
    ADD CONSTRAINT package_status_code_unique UNIQUE (code);


--
-- Name: package_status package_status_displayname_unique; Type: CONSTRAINT; Schema: shipping; Owner: -
--

ALTER TABLE ONLY shipping.package_status
    ADD CONSTRAINT package_status_displayname_unique UNIQUE (display_name);


--
-- Name: package_status package_status_pkey; Type: CONSTRAINT; Schema: shipping; Owner: -
--

ALTER TABLE ONLY shipping.package_status
    ADD CONSTRAINT package_status_pkey PRIMARY KEY (id);


--
-- Name: tempo_package tempo_package_pkey; Type: CONSTRAINT; Schema: shipping; Owner: -
--

ALTER TABLE ONLY shipping.tempo_package
    ADD CONSTRAINT tempo_package_pkey PRIMARY KEY (id);


--
-- Name: tempo_package tempo_package_trackingnumber_unique; Type: CONSTRAINT; Schema: shipping; Owner: -
--

ALTER TABLE ONLY shipping.tempo_package
    ADD CONSTRAINT tempo_package_trackingnumber_unique UNIQUE (tracking_number);


--
-- Name: fk_role_user_role_idx; Type: INDEX; Schema: auth; Owner: -
--

CREATE INDEX fk_role_user_role_idx ON auth.tempo_role_user USING btree (role_id);


--
-- Name: fk_role_user_user_idx; Type: INDEX; Schema: auth; Owner: -
--

CREATE INDEX fk_role_user_user_idx ON auth.tempo_role_user USING btree (user_id);


--
-- Name: fk_session_user_idx; Type: INDEX; Schema: auth; Owner: -
--

CREATE INDEX fk_session_user_idx ON auth.session USING btree (user_id);


--
-- Name: fk_user_client_idx; Type: INDEX; Schema: auth; Owner: -
--

CREATE INDEX fk_user_client_idx ON auth.tempo_user USING btree (client_id);


--
-- Name: fk_business_client_idx; Type: INDEX; Schema: client; Owner: -
--

CREATE INDEX fk_business_client_idx ON client.business USING btree (client_id);


--
-- Name: fk_client_client_idx; Type: INDEX; Schema: client; Owner: -
--

CREATE INDEX fk_client_client_idx ON client.client USING btree (referred_by_client_id);


--
-- Name: fk_client_client_type_idx; Type: INDEX; Schema: client; Owner: -
--

CREATE INDEX fk_client_client_type_idx ON client.client USING btree (type_id);


--
-- Name: fk_delivery_address_client_idx; Type: INDEX; Schema: client; Owner: -
--

CREATE INDEX fk_delivery_address_client_idx ON client.delivery_address USING btree (client_id);


--
-- Name: fk_individual_client_idx; Type: INDEX; Schema: client; Owner: -
--

CREATE INDEX fk_individual_client_idx ON client.individual USING btree (client_id);


--
-- Name: fk_individual_identity_type_idx; Type: INDEX; Schema: client; Owner: -
--

CREATE INDEX fk_individual_identity_type_idx ON client.individual USING btree (identity_type_id);


--
-- Name: fk_warehouse_address_warehouse_type_idx; Type: INDEX; Schema: depot; Owner: -
--

CREATE INDEX fk_warehouse_address_warehouse_type_idx ON depot.warehouse_address USING btree (warehouse_type_id);


--
-- Name: fk_warehouse_cn_warehouse_address_idx; Type: INDEX; Schema: depot; Owner: -
--

CREATE INDEX fk_warehouse_cn_warehouse_address_idx ON depot.warehouse_cn USING btree (warehouse_address_id);


--
-- Name: fk_warehouse_co_warehouse_address_idx; Type: INDEX; Schema: depot; Owner: -
--

CREATE INDEX fk_warehouse_co_warehouse_address_idx ON depot.warehouse_co USING btree (warehouse_address_id);


--
-- Name: fk_warehouse_us_warehouse_address_idx; Type: INDEX; Schema: depot; Owner: -
--

CREATE INDEX fk_warehouse_us_warehouse_address_idx ON depot.warehouse_us USING btree (warehouse_address_id);


--
-- Name: fk_tempo_package_client_idx; Type: INDEX; Schema: shipping; Owner: -
--

CREATE INDEX fk_tempo_package_client_idx ON shipping.tempo_package USING btree (client_id);


--
-- Name: fk_tempo_package_delivery_address_idx; Type: INDEX; Schema: shipping; Owner: -
--

CREATE INDEX fk_tempo_package_delivery_address_idx ON shipping.tempo_package USING btree (delivery_address_id);


--
-- Name: fk_tempo_package_package_status_idx; Type: INDEX; Schema: shipping; Owner: -
--

CREATE INDEX fk_tempo_package_package_status_idx ON shipping.tempo_package USING btree (package_status_id);


--
-- Name: fk_tempo_package_warehouse_address_idx; Type: INDEX; Schema: shipping; Owner: -
--

CREATE INDEX fk_tempo_package_warehouse_address_idx ON shipping.tempo_package USING btree (warehouse_address_id);


--
-- Name: tempo_role_user fk_role_user_role; Type: FK CONSTRAINT; Schema: auth; Owner: -
--

ALTER TABLE ONLY auth.tempo_role_user
    ADD CONSTRAINT fk_role_user_role FOREIGN KEY (role_id) REFERENCES auth.tempo_role(id) ON DELETE CASCADE;


--
-- Name: tempo_role_user fk_role_user_user; Type: FK CONSTRAINT; Schema: auth; Owner: -
--

ALTER TABLE ONLY auth.tempo_role_user
    ADD CONSTRAINT fk_role_user_user FOREIGN KEY (user_id) REFERENCES auth.tempo_user(id) ON DELETE CASCADE;


--
-- Name: session fk_session_user; Type: FK CONSTRAINT; Schema: auth; Owner: -
--

ALTER TABLE ONLY auth.session
    ADD CONSTRAINT fk_session_user FOREIGN KEY (user_id) REFERENCES auth.tempo_user(id) ON DELETE CASCADE;


--
-- Name: tempo_user fk_tempo_user_client; Type: FK CONSTRAINT; Schema: auth; Owner: -
--

ALTER TABLE ONLY auth.tempo_user
    ADD CONSTRAINT fk_tempo_user_client FOREIGN KEY (client_id) REFERENCES client.client(id);


--
-- Name: business fk_business_client; Type: FK CONSTRAINT; Schema: client; Owner: -
--

ALTER TABLE ONLY client.business
    ADD CONSTRAINT fk_business_client FOREIGN KEY (client_id) REFERENCES client.client(id);


--
-- Name: client fk_client_client; Type: FK CONSTRAINT; Schema: client; Owner: -
--

ALTER TABLE ONLY client.client
    ADD CONSTRAINT fk_client_client FOREIGN KEY (referred_by_client_id) REFERENCES client.client(id);


--
-- Name: client fk_client_client_type; Type: FK CONSTRAINT; Schema: client; Owner: -
--

ALTER TABLE ONLY client.client
    ADD CONSTRAINT fk_client_client_type FOREIGN KEY (type_id) REFERENCES client.client_type(id);


--
-- Name: delivery_address fk_delivery_address_client; Type: FK CONSTRAINT; Schema: client; Owner: -
--

ALTER TABLE ONLY client.delivery_address
    ADD CONSTRAINT fk_delivery_address_client FOREIGN KEY (client_id) REFERENCES client.client(id);


--
-- Name: individual fk_individual_client; Type: FK CONSTRAINT; Schema: client; Owner: -
--

ALTER TABLE ONLY client.individual
    ADD CONSTRAINT fk_individual_client FOREIGN KEY (client_id) REFERENCES client.client(id);


--
-- Name: individual fk_individual_identity_type; Type: FK CONSTRAINT; Schema: client; Owner: -
--

ALTER TABLE ONLY client.individual
    ADD CONSTRAINT fk_individual_identity_type FOREIGN KEY (identity_type_id) REFERENCES client.identity_type(id);


--
-- Name: warehouse_address fk_warehouse_address_warehouse_type; Type: FK CONSTRAINT; Schema: depot; Owner: -
--

ALTER TABLE ONLY depot.warehouse_address
    ADD CONSTRAINT fk_warehouse_address_warehouse_type FOREIGN KEY (warehouse_type_id) REFERENCES depot.warehouse_type(id);


--
-- Name: warehouse_cn fk_warehouse_cn_warehouse_address; Type: FK CONSTRAINT; Schema: depot; Owner: -
--

ALTER TABLE ONLY depot.warehouse_cn
    ADD CONSTRAINT fk_warehouse_cn_warehouse_address FOREIGN KEY (warehouse_address_id) REFERENCES depot.warehouse_address(id);


--
-- Name: warehouse_co fk_warehouse_cn_warehouse_address; Type: FK CONSTRAINT; Schema: depot; Owner: -
--

ALTER TABLE ONLY depot.warehouse_co
    ADD CONSTRAINT fk_warehouse_cn_warehouse_address FOREIGN KEY (warehouse_address_id) REFERENCES depot.warehouse_address(id);


--
-- Name: warehouse_us fk_warehouse_us_warehouse_address; Type: FK CONSTRAINT; Schema: depot; Owner: -
--

ALTER TABLE ONLY depot.warehouse_us
    ADD CONSTRAINT fk_warehouse_us_warehouse_address FOREIGN KEY (warehouse_address_id) REFERENCES depot.warehouse_address(id);


--
-- Name: tempo_package fk_tempo_package_client; Type: FK CONSTRAINT; Schema: shipping; Owner: -
--

ALTER TABLE ONLY shipping.tempo_package
    ADD CONSTRAINT fk_tempo_package_client FOREIGN KEY (client_id) REFERENCES client.client(id);


--
-- Name: tempo_package fk_tempo_package_delivery_address; Type: FK CONSTRAINT; Schema: shipping; Owner: -
--

ALTER TABLE ONLY shipping.tempo_package
    ADD CONSTRAINT fk_tempo_package_delivery_address FOREIGN KEY (delivery_address_id) REFERENCES client.delivery_address(id);


--
-- Name: tempo_package fk_tempo_package_package_status; Type: FK CONSTRAINT; Schema: shipping; Owner: -
--

ALTER TABLE ONLY shipping.tempo_package
    ADD CONSTRAINT fk_tempo_package_package_status FOREIGN KEY (package_status_id) REFERENCES shipping.package_status(id);


--
-- Name: tempo_package fk_tempo_package_warehouse_address; Type: FK CONSTRAINT; Schema: shipping; Owner: -
--

ALTER TABLE ONLY shipping.tempo_package
    ADD CONSTRAINT fk_tempo_package_warehouse_address FOREIGN KEY (warehouse_address_id) REFERENCES depot.warehouse_address(id);


--
-- PostgreSQL database dump complete
--

