--
-- PostgreSQL database dump
--

-- Dumped from database version 16.9 (Debian 16.9-1.pgdg120+1)
-- Dumped by pg_dump version 16.9 (Debian 16.9-1.pgdg120+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: auth; Type: SCHEMA; Schema: -; Owner: -
--

CREATE SCHEMA auth;


--
-- Name: client; Type: SCHEMA; Schema: -; Owner: -
--

CREATE SCHEMA client;


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: revoked_token; Type: TABLE; Schema: auth; Owner: -
--

CREATE TABLE auth.revoked_token (
    id bigint NOT NULL,
    revoked_at timestamp(6) without time zone NOT NULL,
    token_hash character varying(64) NOT NULL,
    reason character varying(255)
);


--
-- Name: revoked_token_id_seq; Type: SEQUENCE; Schema: auth; Owner: -
--

ALTER TABLE auth.revoked_token ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME auth.revoked_token_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: session; Type: TABLE; Schema: auth; Owner: -
--

CREATE TABLE auth.session (
    is_active boolean NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    expires_at timestamp(6) without time zone NOT NULL,
    id bigint NOT NULL,
    last_activity_at timestamp(6) without time zone NOT NULL,
    user_id bigint NOT NULL,
    ip_address character varying(45),
    access_token_hash character varying(64) NOT NULL,
    refresh_token_hash character varying(64) NOT NULL,
    user_agent character varying(1024)
);


--
-- Name: session_id_seq; Type: SEQUENCE; Schema: auth; Owner: -
--

ALTER TABLE auth.session ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME auth.session_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tempo_role; Type: TABLE; Schema: auth; Owner: -
--

CREATE TABLE auth.tempo_role (
    id bigint NOT NULL,
    name character varying(50) NOT NULL
);


--
-- Name: tempo_role_id_seq; Type: SEQUENCE; Schema: auth; Owner: -
--

ALTER TABLE auth.tempo_role ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME auth.tempo_role_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tempo_role_user; Type: TABLE; Schema: auth; Owner: -
--

CREATE TABLE auth.tempo_role_user (
    id bigint NOT NULL,
    role_id bigint NOT NULL,
    user_id bigint NOT NULL
);


--
-- Name: tempo_role_user_id_seq; Type: SEQUENCE; Schema: auth; Owner: -
--

ALTER TABLE auth.tempo_role_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME auth.tempo_role_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tempo_user; Type: TABLE; Schema: auth; Owner: -
--

CREATE TABLE auth.tempo_user (
    account_non_locked boolean NOT NULL,
    email_confirmed boolean NOT NULL,
    enabled boolean NOT NULL,
    login_attempts integer,
    client_id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    id bigint NOT NULL,
    last_activity_at timestamp(6) without time zone,
    last_login_at timestamp(6) without time zone,
    modified_at timestamp(6) without time zone NOT NULL,
    recuperation_token_exp_at timestamp(6) without time zone,
    recuperation_token character varying(10),
    username character varying(20) NOT NULL,
    password_hash character varying(150) NOT NULL,
    email character varying(255) NOT NULL
);


--
-- Name: tempo_user_id_seq; Type: SEQUENCE; Schema: auth; Owner: -
--

ALTER TABLE auth.tempo_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME auth.tempo_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: address_type; Type: TABLE; Schema: client; Owner: -
--

CREATE TABLE client.address_type (
    code character varying(4) NOT NULL,
    id bigint NOT NULL,
    display_name character varying(20) NOT NULL
);


--
-- Name: address_type_id_seq; Type: SEQUENCE; Schema: client; Owner: -
--

ALTER TABLE client.address_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME client.address_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: business; Type: TABLE; Schema: client; Owner: -
--

CREATE TABLE client.business (
    client_id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    ruc_number character varying(50) NOT NULL,
    name character varying(100) NOT NULL,
    contact_name character varying(255) NOT NULL
);


--
-- Name: client; Type: TABLE; Schema: client; Owner: -
--

CREATE TABLE client.client (
    terms_version character varying(5),
    created_at timestamp(6) without time zone NOT NULL,
    id bigint NOT NULL,
    referred_by_client_id bigint,
    terms_accepted_at timestamp(6) without time zone,
    type_id bigint NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    phone_number_pri character varying(20) NOT NULL,
    phone_number_sec character varying(20)
);


--
-- Name: client_address; Type: TABLE; Schema: client; Owner: -
--

CREATE TABLE client.client_address (
    is_default boolean NOT NULL,
    address_type_id bigint NOT NULL,
    client_id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    id bigint NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    address_name character varying(100) NOT NULL
);


--
-- Name: client_address_id_seq; Type: SEQUENCE; Schema: client; Owner: -
--

ALTER TABLE client.client_address ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME client.client_address_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: client_id_seq; Type: SEQUENCE; Schema: client; Owner: -
--

ALTER TABLE client.client ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME client.client_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: client_type; Type: TABLE; Schema: client; Owner: -
--

CREATE TABLE client.client_type (
    code character varying(4) NOT NULL,
    id bigint NOT NULL,
    display_name character varying(20) NOT NULL
);


--
-- Name: client_type_id_seq; Type: SEQUENCE; Schema: client; Owner: -
--

ALTER TABLE client.client_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME client.client_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: foreign_address; Type: TABLE; Schema: client; Owner: -
--

CREATE TABLE client.foreign_address (
    country_code character varying(2) NOT NULL,
    client_address_id bigint NOT NULL,
    postal_code character varying(20) NOT NULL,
    state_province character varying(50) NOT NULL,
    city character varying(85) NOT NULL,
    street_line_2 character varying(100),
    street_line_1 character varying(200) NOT NULL
);


--
-- Name: identity_type; Type: TABLE; Schema: client; Owner: -
--

CREATE TABLE client.identity_type (
    code character varying(4) NOT NULL,
    id bigint NOT NULL,
    display_name character varying(20) NOT NULL
);


--
-- Name: identity_type_id_seq; Type: SEQUENCE; Schema: client; Owner: -
--

ALTER TABLE client.identity_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME client.identity_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: individual; Type: TABLE; Schema: client; Owner: -
--

CREATE TABLE client.individual (
    client_id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    date_of_birth timestamp(6) without time zone NOT NULL,
    identity_type_id bigint NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    identity_number character varying(20) NOT NULL,
    first_name character varying(255) NOT NULL,
    last_name character varying(255) NOT NULL
);


--
-- Name: pty_address; Type: TABLE; Schema: client; Owner: -
--

CREATE TABLE client.pty_address (
    country character varying(2) NOT NULL,
    client_address_id bigint NOT NULL,
    province character varying(25) NOT NULL,
    district character varying(50) NOT NULL,
    corregimiento character varying(100) NOT NULL,
    address character varying(250) NOT NULL
);


--
-- Name: revoked_token revoked_token_pkey; Type: CONSTRAINT; Schema: auth; Owner: -
--

ALTER TABLE ONLY auth.revoked_token
    ADD CONSTRAINT revoked_token_pkey PRIMARY KEY (id);


--
-- Name: revoked_token revoked_token_token_hash_key; Type: CONSTRAINT; Schema: auth; Owner: -
--

ALTER TABLE ONLY auth.revoked_token
    ADD CONSTRAINT revoked_token_token_hash_key UNIQUE (token_hash);


--
-- Name: tempo_role role_name_unique; Type: CONSTRAINT; Schema: auth; Owner: -
--

ALTER TABLE ONLY auth.tempo_role
    ADD CONSTRAINT role_name_unique UNIQUE (name);


--
-- Name: tempo_role_user role_user_roleid_userid_unique; Type: CONSTRAINT; Schema: auth; Owner: -
--

ALTER TABLE ONLY auth.tempo_role_user
    ADD CONSTRAINT role_user_roleid_userid_unique UNIQUE (role_id, user_id);


--
-- Name: session session_access_token_hash_key; Type: CONSTRAINT; Schema: auth; Owner: -
--

ALTER TABLE ONLY auth.session
    ADD CONSTRAINT session_access_token_hash_key UNIQUE (access_token_hash);


--
-- Name: session session_pkey; Type: CONSTRAINT; Schema: auth; Owner: -
--

ALTER TABLE ONLY auth.session
    ADD CONSTRAINT session_pkey PRIMARY KEY (id);


--
-- Name: session session_refresh_token_hash_key; Type: CONSTRAINT; Schema: auth; Owner: -
--

ALTER TABLE ONLY auth.session
    ADD CONSTRAINT session_refresh_token_hash_key UNIQUE (refresh_token_hash);


--
-- Name: tempo_role tempo_role_pkey; Type: CONSTRAINT; Schema: auth; Owner: -
--

ALTER TABLE ONLY auth.tempo_role
    ADD CONSTRAINT tempo_role_pkey PRIMARY KEY (id);


--
-- Name: tempo_role_user tempo_role_user_pkey; Type: CONSTRAINT; Schema: auth; Owner: -
--

ALTER TABLE ONLY auth.tempo_role_user
    ADD CONSTRAINT tempo_role_user_pkey PRIMARY KEY (id);


--
-- Name: tempo_user tempo_user_client_id_key; Type: CONSTRAINT; Schema: auth; Owner: -
--

ALTER TABLE ONLY auth.tempo_user
    ADD CONSTRAINT tempo_user_client_id_key UNIQUE (client_id);


--
-- Name: tempo_user tempo_user_pkey; Type: CONSTRAINT; Schema: auth; Owner: -
--

ALTER TABLE ONLY auth.tempo_user
    ADD CONSTRAINT tempo_user_pkey PRIMARY KEY (id);


--
-- Name: tempo_user user_email_unique; Type: CONSTRAINT; Schema: auth; Owner: -
--

ALTER TABLE ONLY auth.tempo_user
    ADD CONSTRAINT user_email_unique UNIQUE (email);


--
-- Name: tempo_user user_username_unique; Type: CONSTRAINT; Schema: auth; Owner: -
--

ALTER TABLE ONLY auth.tempo_user
    ADD CONSTRAINT user_username_unique UNIQUE (username);


--
-- Name: address_type address_type_code_unique; Type: CONSTRAINT; Schema: client; Owner: -
--

ALTER TABLE ONLY client.address_type
    ADD CONSTRAINT address_type_code_unique UNIQUE (code);


--
-- Name: address_type address_type_displayname_unique; Type: CONSTRAINT; Schema: client; Owner: -
--

ALTER TABLE ONLY client.address_type
    ADD CONSTRAINT address_type_displayname_unique UNIQUE (display_name);


--
-- Name: address_type address_type_pkey; Type: CONSTRAINT; Schema: client; Owner: -
--

ALTER TABLE ONLY client.address_type
    ADD CONSTRAINT address_type_pkey PRIMARY KEY (id);


--
-- Name: business business_name_unique; Type: CONSTRAINT; Schema: client; Owner: -
--

ALTER TABLE ONLY client.business
    ADD CONSTRAINT business_name_unique UNIQUE (name);


--
-- Name: business business_pkey; Type: CONSTRAINT; Schema: client; Owner: -
--

ALTER TABLE ONLY client.business
    ADD CONSTRAINT business_pkey PRIMARY KEY (client_id);


--
-- Name: business business_rucnumber_unique; Type: CONSTRAINT; Schema: client; Owner: -
--

ALTER TABLE ONLY client.business
    ADD CONSTRAINT business_rucnumber_unique UNIQUE (ruc_number);


--
-- Name: client_address client_address_clientid_addressname_unique; Type: CONSTRAINT; Schema: client; Owner: -
--

ALTER TABLE ONLY client.client_address
    ADD CONSTRAINT client_address_clientid_addressname_unique UNIQUE (client_id, address_name);


--
-- Name: client_address client_address_pkey; Type: CONSTRAINT; Schema: client; Owner: -
--

ALTER TABLE ONLY client.client_address
    ADD CONSTRAINT client_address_pkey PRIMARY KEY (id);


--
-- Name: client client_pkey; Type: CONSTRAINT; Schema: client; Owner: -
--

ALTER TABLE ONLY client.client
    ADD CONSTRAINT client_pkey PRIMARY KEY (id);


--
-- Name: client_type client_type_code_unique; Type: CONSTRAINT; Schema: client; Owner: -
--

ALTER TABLE ONLY client.client_type
    ADD CONSTRAINT client_type_code_unique UNIQUE (code);


--
-- Name: client_type client_type_displayname_unique; Type: CONSTRAINT; Schema: client; Owner: -
--

ALTER TABLE ONLY client.client_type
    ADD CONSTRAINT client_type_displayname_unique UNIQUE (display_name);


--
-- Name: client_type client_type_pkey; Type: CONSTRAINT; Schema: client; Owner: -
--

ALTER TABLE ONLY client.client_type
    ADD CONSTRAINT client_type_pkey PRIMARY KEY (id);


--
-- Name: foreign_address foreign_address_pkey; Type: CONSTRAINT; Schema: client; Owner: -
--

ALTER TABLE ONLY client.foreign_address
    ADD CONSTRAINT foreign_address_pkey PRIMARY KEY (client_address_id);


--
-- Name: identity_type identity_type_code_unique; Type: CONSTRAINT; Schema: client; Owner: -
--

ALTER TABLE ONLY client.identity_type
    ADD CONSTRAINT identity_type_code_unique UNIQUE (code);


--
-- Name: identity_type identity_type_displayname_unique; Type: CONSTRAINT; Schema: client; Owner: -
--

ALTER TABLE ONLY client.identity_type
    ADD CONSTRAINT identity_type_displayname_unique UNIQUE (display_name);


--
-- Name: identity_type identity_type_pkey; Type: CONSTRAINT; Schema: client; Owner: -
--

ALTER TABLE ONLY client.identity_type
    ADD CONSTRAINT identity_type_pkey PRIMARY KEY (id);


--
-- Name: individual individual_identitynumber_unique; Type: CONSTRAINT; Schema: client; Owner: -
--

ALTER TABLE ONLY client.individual
    ADD CONSTRAINT individual_identitynumber_unique UNIQUE (identity_number);


--
-- Name: individual individual_pkey; Type: CONSTRAINT; Schema: client; Owner: -
--

ALTER TABLE ONLY client.individual
    ADD CONSTRAINT individual_pkey PRIMARY KEY (client_id);


--
-- Name: pty_address pty_address_pkey; Type: CONSTRAINT; Schema: client; Owner: -
--

ALTER TABLE ONLY client.pty_address
    ADD CONSTRAINT pty_address_pkey PRIMARY KEY (client_address_id);


--
-- Name: fk_role_user_role_idx; Type: INDEX; Schema: auth; Owner: -
--

CREATE INDEX fk_role_user_role_idx ON auth.tempo_role_user USING btree (role_id);


--
-- Name: fk_role_user_user_idx; Type: INDEX; Schema: auth; Owner: -
--

CREATE INDEX fk_role_user_user_idx ON auth.tempo_role_user USING btree (user_id);


--
-- Name: fk_session_user_idx; Type: INDEX; Schema: auth; Owner: -
--

CREATE INDEX fk_session_user_idx ON auth.session USING btree (user_id);


--
-- Name: fk_user_client_idx; Type: INDEX; Schema: auth; Owner: -
--

CREATE INDEX fk_user_client_idx ON auth.tempo_user USING btree (client_id);


--
-- Name: fk_client_address_address_type_idx; Type: INDEX; Schema: client; Owner: -
--

CREATE INDEX fk_client_address_address_type_idx ON client.client_address USING btree (address_type_id);


--
-- Name: fk_client_client_idx; Type: INDEX; Schema: client; Owner: -
--

CREATE INDEX fk_client_client_idx ON client.client USING btree (referred_by_client_id);


--
-- Name: fk_client_client_type_idx; Type: INDEX; Schema: client; Owner: -
--

CREATE INDEX fk_client_client_type_idx ON client.client USING btree (type_id);


--
-- Name: fk_foreign_address_client_address_idx; Type: INDEX; Schema: client; Owner: -
--

CREATE INDEX fk_foreign_address_client_address_idx ON client.foreign_address USING btree (client_address_id);


--
-- Name: fk_individual_client_idx; Type: INDEX; Schema: client; Owner: -
--

CREATE INDEX fk_individual_client_idx ON client.individual USING btree (client_id);


--
-- Name: fk_individual_identity_type_idx; Type: INDEX; Schema: client; Owner: -
--

CREATE INDEX fk_individual_identity_type_idx ON client.individual USING btree (identity_type_id);


--
-- Name: fk_pty_address_client_address_idx; Type: INDEX; Schema: client; Owner: -
--

CREATE INDEX fk_pty_address_client_address_idx ON client.pty_address USING btree (client_address_id);


--
-- Name: tempo_role_user fk_role_user_role; Type: FK CONSTRAINT; Schema: auth; Owner: -
--

ALTER TABLE ONLY auth.tempo_role_user
    ADD CONSTRAINT fk_role_user_role FOREIGN KEY (role_id) REFERENCES auth.tempo_role(id) ON DELETE CASCADE;


--
-- Name: tempo_role_user fk_role_user_user; Type: FK CONSTRAINT; Schema: auth; Owner: -
--

ALTER TABLE ONLY auth.tempo_role_user
    ADD CONSTRAINT fk_role_user_user FOREIGN KEY (user_id) REFERENCES auth.tempo_user(id) ON DELETE CASCADE;


--
-- Name: session fk_session_user; Type: FK CONSTRAINT; Schema: auth; Owner: -
--

ALTER TABLE ONLY auth.session
    ADD CONSTRAINT fk_session_user FOREIGN KEY (user_id) REFERENCES auth.tempo_user(id) ON DELETE CASCADE;


--
-- Name: tempo_user fk_tempo_user_client; Type: FK CONSTRAINT; Schema: auth; Owner: -
--

ALTER TABLE ONLY auth.tempo_user
    ADD CONSTRAINT fk_tempo_user_client FOREIGN KEY (client_id) REFERENCES client.client(id);


--
-- Name: business fk_business_client; Type: FK CONSTRAINT; Schema: client; Owner: -
--

ALTER TABLE ONLY client.business
    ADD CONSTRAINT fk_business_client FOREIGN KEY (client_id) REFERENCES client.client(id);


--
-- Name: client_address fk_client_address_address_type; Type: FK CONSTRAINT; Schema: client; Owner: -
--

ALTER TABLE ONLY client.client_address
    ADD CONSTRAINT fk_client_address_address_type FOREIGN KEY (address_type_id) REFERENCES client.address_type(id);


--
-- Name: client_address fk_client_address_client; Type: FK CONSTRAINT; Schema: client; Owner: -
--

ALTER TABLE ONLY client.client_address
    ADD CONSTRAINT fk_client_address_client FOREIGN KEY (client_id) REFERENCES client.client(id);


--
-- Name: client fk_client_client; Type: FK CONSTRAINT; Schema: client; Owner: -
--

ALTER TABLE ONLY client.client
    ADD CONSTRAINT fk_client_client FOREIGN KEY (referred_by_client_id) REFERENCES client.client(id);


--
-- Name: client fk_client_client_type; Type: FK CONSTRAINT; Schema: client; Owner: -
--

ALTER TABLE ONLY client.client
    ADD CONSTRAINT fk_client_client_type FOREIGN KEY (type_id) REFERENCES client.client_type(id);


--
-- Name: foreign_address fk_foreign_address_client_address; Type: FK CONSTRAINT; Schema: client; Owner: -
--

ALTER TABLE ONLY client.foreign_address
    ADD CONSTRAINT fk_foreign_address_client_address FOREIGN KEY (client_address_id) REFERENCES client.client_address(id);


--
-- Name: individual fk_individual_client; Type: FK CONSTRAINT; Schema: client; Owner: -
--

ALTER TABLE ONLY client.individual
    ADD CONSTRAINT fk_individual_client FOREIGN KEY (client_id) REFERENCES client.client(id);


--
-- Name: individual fk_individual_identity_type; Type: FK CONSTRAINT; Schema: client; Owner: -
--

ALTER TABLE ONLY client.individual
    ADD CONSTRAINT fk_individual_identity_type FOREIGN KEY (identity_type_id) REFERENCES client.identity_type(id);


--
-- Name: pty_address fk_pty_address_client_address; Type: FK CONSTRAINT; Schema: client; Owner: -
--

ALTER TABLE ONLY client.pty_address
    ADD CONSTRAINT fk_pty_address_client_address FOREIGN KEY (client_address_id) REFERENCES client.client_address(id);


--
-- PostgreSQL database dump complete
--

