--
-- PostgreSQL database dump
--

-- Dumped from database version 16.9 (Debian 16.9-1.pgdg120+1)
-- Dumped by pg_dump version 16.9 (Debian 16.9-1.pgdg120+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: auth; Type: SCHEMA; Schema: -; Owner: -
--

CREATE SCHEMA auth;


--
-- Name: public; Type: SCHEMA; Schema: -; Owner: -
--

CREATE SCHEMA public;


--
-- Name: SCHEMA public; Type: COMMENT; Schema: -; Owner: -
--

COMMENT ON SCHEMA public IS 'standard public schema';


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: revoked_token; Type: TABLE; Schema: auth; Owner: -
--

CREATE TABLE auth.revoked_token (
    id bigint NOT NULL,
    revoked_at timestamp(6) without time zone NOT NULL,
    reason character varying(255),
    token_hash character varying(255) NOT NULL
);


--
-- Name: revoked_token_id_seq; Type: SEQUENCE; Schema: auth; Owner: -
--

ALTER TABLE auth.revoked_token ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME auth.revoked_token_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: session; Type: TABLE; Schema: auth; Owner: -
--

CREATE TABLE auth.session (
    is_active boolean NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    expires_at timestamp(6) without time zone NOT NULL,
    id bigint NOT NULL,
    last_activity_at timestamp(6) without time zone NOT NULL,
    user_id bigint NOT NULL,
    "ip_a ddress" character varying(45),
    access_token_hash character varying(64) NOT NULL,
    refresh_token_hash character varying(64) NOT NULL,
    user_agent character varying(1024)
);


--
-- Name: session_id_seq; Type: SEQUENCE; Schema: auth; Owner: -
--

ALTER TABLE auth.session ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME auth.session_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tempo_role; Type: TABLE; Schema: auth; Owner: -
--

CREATE TABLE auth.tempo_role (
    id bigint NOT NULL,
    name character varying(50) NOT NULL
);


--
-- Name: tempo_role_id_seq; Type: SEQUENCE; Schema: auth; Owner: -
--

ALTER TABLE auth.tempo_role ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME auth.tempo_role_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tempo_role_user; Type: TABLE; Schema: auth; Owner: -
--

CREATE TABLE auth.tempo_role_user (
    id bigint NOT NULL,
    role_id bigint NOT NULL,
    user_id bigint NOT NULL
);


--
-- Name: tempo_role_user_id_seq; Type: SEQUENCE; Schema: auth; Owner: -
--

ALTER TABLE auth.tempo_role_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME auth.tempo_role_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tempo_user; Type: TABLE; Schema: auth; Owner: -
--

CREATE TABLE auth.tempo_user (
    account_non_locked boolean NOT NULL,
    email_confirmed boolean NOT NULL,
    enabled boolean NOT NULL,
    login_attempts integer,
    created_at timestamp(6) without time zone NOT NULL,
    id bigint NOT NULL,
    last_activity_at timestamp(6) without time zone,
    last_login_at timestamp(6) without time zone,
    modified_at timestamp(6) without time zone NOT NULL,
    recuperation_token_exp_at timestamp(6) without time zone,
    recuperation_token character varying(10),
    username character varying(20) NOT NULL,
    password_hash character varying(150) NOT NULL,
    email character varying(255) NOT NULL
);


--
-- Name: tempo_user_id_seq; Type: SEQUENCE; Schema: auth; Owner: -
--

ALTER TABLE auth.tempo_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME auth.tempo_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: revoked_token revoked_token_pkey; Type: CONSTRAINT; Schema: auth; Owner: -
--

ALTER TABLE ONLY auth.revoked_token
    ADD CONSTRAINT revoked_token_pkey PRIMARY KEY (id);


--
-- Name: revoked_token revoked_token_token_hash_key; Type: CONSTRAINT; Schema: auth; Owner: -
--

ALTER TABLE ONLY auth.revoked_token
    ADD CONSTRAINT revoked_token_token_hash_key UNIQUE (token_hash);


--
-- Name: tempo_role role_name_unique; Type: CONSTRAINT; Schema: auth; Owner: -
--

ALTER TABLE ONLY auth.tempo_role
    ADD CONSTRAINT role_name_unique UNIQUE (name);


--
-- Name: tempo_role_user role_user_roleid_userid_unique; Type: CONSTRAINT; Schema: auth; Owner: -
--

ALTER TABLE ONLY auth.tempo_role_user
    ADD CONSTRAINT role_user_roleid_userid_unique UNIQUE (role_id, user_id);


--
-- Name: session session_access_token_hash_key; Type: CONSTRAINT; Schema: auth; Owner: -
--

ALTER TABLE ONLY auth.session
    ADD CONSTRAINT session_access_token_hash_key UNIQUE (access_token_hash);


--
-- Name: session session_pkey; Type: CONSTRAINT; Schema: auth; Owner: -
--

ALTER TABLE ONLY auth.session
    ADD CONSTRAINT session_pkey PRIMARY KEY (id);


--
-- Name: session session_refresh_token_hash_key; Type: CONSTRAINT; Schema: auth; Owner: -
--

ALTER TABLE ONLY auth.session
    ADD CONSTRAINT session_refresh_token_hash_key UNIQUE (refresh_token_hash);


--
-- Name: tempo_role tempo_role_pkey; Type: CONSTRAINT; Schema: auth; Owner: -
--

ALTER TABLE ONLY auth.tempo_role
    ADD CONSTRAINT tempo_role_pkey PRIMARY KEY (id);


--
-- Name: tempo_role_user tempo_role_user_pkey; Type: CONSTRAINT; Schema: auth; Owner: -
--

ALTER TABLE ONLY auth.tempo_role_user
    ADD CONSTRAINT tempo_role_user_pkey PRIMARY KEY (id);


--
-- Name: tempo_user tempo_user_pkey; Type: CONSTRAINT; Schema: auth; Owner: -
--

ALTER TABLE ONLY auth.tempo_user
    ADD CONSTRAINT tempo_user_pkey PRIMARY KEY (id);


--
-- Name: tempo_user user_email_unique; Type: CONSTRAINT; Schema: auth; Owner: -
--

ALTER TABLE ONLY auth.tempo_user
    ADD CONSTRAINT user_email_unique UNIQUE (email);


--
-- Name: tempo_user user_username_unique; Type: CONSTRAINT; Schema: auth; Owner: -
--

ALTER TABLE ONLY auth.tempo_user
    ADD CONSTRAINT user_username_unique UNIQUE (username);


--
-- Name: fk_role_user_role_idx; Type: INDEX; Schema: auth; Owner: -
--

CREATE INDEX fk_role_user_role_idx ON auth.tempo_role_user USING btree (role_id);


--
-- Name: fk_role_user_user_idx; Type: INDEX; Schema: auth; Owner: -
--

CREATE INDEX fk_role_user_user_idx ON auth.tempo_role_user USING btree (user_id);


--
-- Name: fk_session_user_idx; Type: INDEX; Schema: auth; Owner: -
--

CREATE INDEX fk_session_user_idx ON auth.session USING btree (user_id);


--
-- Name: tempo_role_user fk_role_user_role; Type: FK CONSTRAINT; Schema: auth; Owner: -
--

ALTER TABLE ONLY auth.tempo_role_user
    ADD CONSTRAINT fk_role_user_role FOREIGN KEY (role_id) REFERENCES auth.tempo_role(id);


--
-- Name: tempo_role_user fk_role_user_user; Type: FK CONSTRAINT; Schema: auth; Owner: -
--

ALTER TABLE ONLY auth.tempo_role_user
    ADD CONSTRAINT fk_role_user_user FOREIGN KEY (user_id) REFERENCES auth.tempo_user(id);


--
-- Name: session fk_session_user; Type: FK CONSTRAINT; Schema: auth; Owner: -
--

ALTER TABLE ONLY auth.session
    ADD CONSTRAINT fk_session_user FOREIGN KEY (user_id) REFERENCES auth.tempo_user(id);


--
-- PostgreSQL database dump complete
--

