spring:
  main:
    web-application-type: none   # no levantes el servidor web

  flyway:
    enabled: false               # no aplicar migraciones en este run

  jpa:
    hibernate:
      ddl-auto: none             # no tocar la BD
    properties:
      # Generación de esquema a archivo (JPA/Jakarta)
      jakarta.persistence.schema-generation.scripts.action: create
      # OJO: este path es el que sobrescribiremos por env var a /out/V1__init.sql
      jakarta.persistence.schema-generation.scripts.create-target: ./generated/V1__init.sql
      jakarta.persistence.schema-generation.create-source: metadata

      # Conveniencias
      hibernate.format_sql: true
      hibernate.physical_naming_strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
      hibernate.globally_quoted_identifiers: true
