spring:
  application:
    name: tempo-cargo-api

  jackson:
    default-property-inclusion: non_null
    serialization:
      write-dates-as-timestamps: false
    time-zone: UTC

  mvc:
    problemdetails:
      enabled: true

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate.jdbc.time_zone: UTC
      hibernate.format_sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration

  security:
    oauth2:
          resourceserver:
            jwt:
              secret: ${JWT_SECRET:change-me-32+chars}

jwt:
  secret: ${JWT_SECRET:change-me-32+chars}
  accessTokenValiditySec: ${JWT_ACCESS_TOKEN_VALIDITY_SEC:900}
  refreshTokenValiditySec: ${JWT_REFRESH_TOKEN_VALIDITY_SEC:1209600}

server:
  port: 8080
  forward-headers-strategy: framework

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,threaddump,httpexchanges
  endpoint:
    health:
      probes:
        enabled: true

logging:
  level:
    org.springframework: INFO
    org.springframework.security: TRACE
    org.hibernate.SQL: INFO
    org.hibernate.type.descriptor.sql: WARN