/* =============================================================================
   V1__init.sql  —  Base DDL bootstrap
   Proyecto    : TempoCargo (PostgreSQL)
   Objetivo    : Crear esquemas, tablas, identidades, constraints, índices y FKs.
   Fuente      : Extraído de pg_dump 16.9 — contenido preservado 1:1.
   Notas       : No se modificó ninguna sentencia; solo se mejoró la estructura
                 visual y los comentarios. Flyway ejecuta en transacción por
                 defecto (no añadimos BEGIN/COMMIT manuales).
   ========================================================================== */

-- ─────────────────────────────────────────────────────────────────────────────
-- Configuración de sesión (preservada de pg_dump)
-- ─────────────────────────────────────────────────────────────────────────────
SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

-- ─────────────────────────────────────────────────────────────────────────────
-- ESQUEMAS
-- ─────────────────────────────────────────────────────────────────────────────
CREATE SCHEMA auth;
CREATE SCHEMA client;
CREATE SCHEMA depot;
CREATE SCHEMA shipping;

SET default_tablespace = '';
SET default_table_access_method = heap;

-- ─────────────────────────────────────────────────────────────────────────────
-- TABLAS (auth)
-- ─────────────────────────────────────────────────────────────────────────────
CREATE TABLE auth.revoked_token (
    id bigint NOT NULL,
    revoked_at timestamp(6) without time zone NOT NULL,
    token_hash character varying(64) NOT NULL
);

ALTER TABLE auth.revoked_token ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME auth.revoked_token_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE auth.session (
    is_active boolean NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    expires_at timestamp(6) without time zone NOT NULL,
    id bigint NOT NULL,
    last_activity_at timestamp(6) without time zone NOT NULL,
    user_id bigint NOT NULL,
    ip_address character varying(45),
    access_token_hash character varying(64) NOT NULL,
    refresh_token_hash character varying(64) NOT NULL,
    user_agent character varying(1024)
);

ALTER TABLE auth.session ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME auth.session_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE auth.tempo_role (
    id bigint NOT NULL,
    name character varying(50) NOT NULL
);

ALTER TABLE auth.tempo_role ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME auth.tempo_role_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE auth.tempo_role_user (
    id bigint NOT NULL,
    role_id bigint NOT NULL,
    user_id bigint NOT NULL
);

ALTER TABLE auth.tempo_role_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME auth.tempo_role_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE auth.tempo_user (
    account_non_locked boolean NOT NULL,
    email_confirmed boolean NOT NULL,
    enabled boolean NOT NULL,
    login_attempts integer,
    client_id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    id bigint NOT NULL,
    last_activity_at timestamp(6) without time zone,
    last_login_at timestamp(6) without time zone,
    recuperation_token_exp_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone NOT NULL,
    recuperation_token character varying(10),
    username character varying(30) NOT NULL,
    password_hash character varying(150) NOT NULL,
    email character varying(255) NOT NULL
);

ALTER TABLE auth.tempo_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME auth.tempo_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

-- ─────────────────────────────────────────────────────────────────────────────
-- TABLAS (client)
-- ─────────────────────────────────────────────────────────────────────────────
CREATE TABLE client.business (
    client_id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    name_code character varying(18) NOT NULL,
    ruc_number character varying(50) NOT NULL,
    name character varying(100) NOT NULL,
    contact_name character varying(255) NOT NULL
);

CREATE TABLE client.client (
    po_box_number integer NOT NULL,
    terms_version character varying(5),
    created_at timestamp(6) without time zone NOT NULL,
    id bigint NOT NULL,
    referred_by_client_id bigint,
    terms_accepted_at timestamp(6) without time zone,
    type_id bigint NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    phone_number_pri character varying(20) NOT NULL,
    phone_number_sec character varying(20)
);

ALTER TABLE client.client ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME client.client_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE client.client_type (
    code character varying(4) NOT NULL,
    id bigint NOT NULL,
    display_name character varying(20) NOT NULL
);

ALTER TABLE client.client_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME client.client_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE client.delivery_address (
    country character varying(2) NOT NULL,
    is_default boolean NOT NULL,
    client_id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    id bigint NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    province character varying(25) NOT NULL,
    address_name character varying(30) NOT NULL,
    district character varying(50) NOT NULL,
    corregimiento character varying(100) NOT NULL,
    address character varying(300) NOT NULL
);

ALTER TABLE client.delivery_address ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME client.delivery_address_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE client.identity_type (
    code character varying(4) NOT NULL,
    id bigint NOT NULL,
    display_name character varying(20) NOT NULL
);

ALTER TABLE client.identity_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME client.identity_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE client.individual (
    client_id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    date_of_birth DATE NOT NULL,
    identity_type_id bigint NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    name_code character varying(18) NOT NULL,
    identity_number character varying(20) NOT NULL,
    first_name character varying(255) NOT NULL,
    last_name character varying(255) NOT NULL
);

-- ─────────────────────────────────────────────────────────────────────────────
-- TABLAS (depot)
-- ─────────────────────────────────────────────────────────────────────────────
CREATE TABLE depot.warehouse_address (
    is_active boolean NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    id bigint NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    warehouse_type_id bigint NOT NULL,
    warehouse_name character varying(25) NOT NULL
);

ALTER TABLE depot.warehouse_address ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME depot.warehouse_address_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE depot.warehouse_cn (
    warehouse_address_id bigint NOT NULL,
    phone_number character varying(20),
    full_address_cn text NOT NULL
);

CREATE TABLE depot.warehouse_co (
    country_code character varying(2) NOT NULL,
    postal_code character varying(6) NOT NULL,
    warehouse_address_id bigint NOT NULL,
    phone_number character varying(20),
    department character varying(30) NOT NULL,
    city character varying(50) NOT NULL,
    barrio character varying(100) NOT NULL,
    street_line character varying(300) NOT NULL
);

CREATE TABLE depot.warehouse_type (
    code character varying(2) NOT NULL,
    id bigint NOT NULL,
    display_name character varying(20) NOT NULL
);

ALTER TABLE depot.warehouse_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME depot.warehouse_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE depot.warehouse_us (
    country_code character varying(2) NOT NULL,
    warehouse_address_id bigint NOT NULL,
    phone_number character varying(15),
    postal_code character varying(20) NOT NULL,
    state_province character varying(50) NOT NULL,
    city character varying(85) NOT NULL,
    street_line_2 character varying(100),
    street_line_1 character varying(200) NOT NULL
);

-- ─────────────────────────────────────────────────────────────────────────────
-- TABLAS (shipping)
-- ─────────────────────────────────────────────────────────────────────────────
CREATE TABLE shipping.package_status (
    code character varying(4) NOT NULL,
    id bigint NOT NULL,
    display_name character varying(20) NOT NULL
);

ALTER TABLE shipping.package_status ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME shipping.package_status_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE shipping.tempo_package (
    client_id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    delivery_address_id bigint,
    id bigint NOT NULL,
    package_status_id bigint NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    warehouse_address_id bigint NOT NULL,
    tracking_number character varying(30) NOT NULL
);

ALTER TABLE shipping.tempo_package ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME shipping.tempo_package_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

-- ─────────────────────────────────────────────────────────────────────────────
-- CONSTRAINTS (PK & UNIQUE)
-- ─────────────────────────────────────────────────────────────────────────────
ALTER TABLE ONLY auth.revoked_token
    ADD CONSTRAINT revoked_token_pkey PRIMARY KEY (id);

ALTER TABLE ONLY auth.revoked_token
    ADD CONSTRAINT revoked_token_token_hash_key UNIQUE (token_hash);

ALTER TABLE ONLY auth.tempo_role
    ADD CONSTRAINT role_name_unique UNIQUE (name);

ALTER TABLE ONLY auth.tempo_role_user
    ADD CONSTRAINT role_user_roleid_userid_unique UNIQUE (role_id, user_id);

ALTER TABLE ONLY auth.session
    ADD CONSTRAINT session_access_token_hash_key UNIQUE (access_token_hash);

ALTER TABLE ONLY auth.session
    ADD CONSTRAINT session_pkey PRIMARY KEY (id);

ALTER TABLE ONLY auth.session
    ADD CONSTRAINT session_refresh_token_hash_key UNIQUE (refresh_token_hash);

ALTER TABLE ONLY auth.tempo_role
    ADD CONSTRAINT tempo_role_pkey PRIMARY KEY (id);

ALTER TABLE ONLY auth.tempo_role_user
    ADD CONSTRAINT tempo_role_user_pkey PRIMARY KEY (id);

ALTER TABLE ONLY auth.tempo_user
    ADD CONSTRAINT tempo_user_client_id_key UNIQUE (client_id);

ALTER TABLE ONLY auth.tempo_user
    ADD CONSTRAINT tempo_user_pkey PRIMARY KEY (id);

ALTER TABLE ONLY auth.tempo_user
    ADD CONSTRAINT user_email_unique UNIQUE (email);

ALTER TABLE ONLY auth.tempo_user
    ADD CONSTRAINT user_username_unique UNIQUE (username);

ALTER TABLE ONLY client.business
    ADD CONSTRAINT business_name_unique UNIQUE (name);

ALTER TABLE ONLY client.business
    ADD CONSTRAINT business_namecode_unique UNIQUE (name_code);

ALTER TABLE ONLY client.business
    ADD CONSTRAINT business_pkey PRIMARY KEY (client_id);

ALTER TABLE ONLY client.business
    ADD CONSTRAINT business_rucnumber_unique UNIQUE (ruc_number);

ALTER TABLE ONLY client.client
    ADD CONSTRAINT client_pkey PRIMARY KEY (id);

ALTER TABLE ONLY client.client
    ADD CONSTRAINT client_poboxnumber_unique UNIQUE (po_box_number);

ALTER TABLE ONLY client.client_type
    ADD CONSTRAINT client_type_code_unique UNIQUE (code);

ALTER TABLE ONLY client.client_type
    ADD CONSTRAINT client_type_displayname_unique UNIQUE (display_name);

ALTER TABLE ONLY client.client_type
    ADD CONSTRAINT client_type_pkey PRIMARY KEY (id);

ALTER TABLE ONLY client.delivery_address
    ADD CONSTRAINT delivery_address_clientid_addressname_unique UNIQUE (client_id, address_name);

ALTER TABLE ONLY client.delivery_address
    ADD CONSTRAINT delivery_address_pkey PRIMARY KEY (id);

ALTER TABLE ONLY client.identity_type
    ADD CONSTRAINT identity_type_code_unique UNIQUE (code);

ALTER TABLE ONLY client.identity_type
    ADD CONSTRAINT identity_type_displayname_unique UNIQUE (display_name);

ALTER TABLE ONLY client.identity_type
    ADD CONSTRAINT identity_type_pkey PRIMARY KEY (id);

ALTER TABLE ONLY client.individual
    ADD CONSTRAINT individual_identitynumber_unique UNIQUE (identity_number);

ALTER TABLE ONLY client.individual
    ADD CONSTRAINT individual_namecode_unique UNIQUE (name_code);

ALTER TABLE ONLY client.individual
    ADD CONSTRAINT individual_pkey PRIMARY KEY (client_id);

ALTER TABLE ONLY depot.warehouse_address
    ADD CONSTRAINT warehouse_address_pkey PRIMARY KEY (id);

ALTER TABLE ONLY depot.warehouse_address
    ADD CONSTRAINT warehouse_address_warehousename_unique UNIQUE (warehouse_name);

ALTER TABLE ONLY depot.warehouse_cn
    ADD CONSTRAINT warehouse_cn_pkey PRIMARY KEY (warehouse_address_id);

ALTER TABLE ONLY depot.warehouse_co
    ADD CONSTRAINT warehouse_co_pkey PRIMARY KEY (warehouse_address_id);

ALTER TABLE ONLY depot.warehouse_type
    ADD CONSTRAINT warehouse_type_code_unique UNIQUE (code);

ALTER TABLE ONLY depot.warehouse_type
    ADD CONSTRAINT warehouse_type_displayname_unique UNIQUE (display_name);

ALTER TABLE ONLY depot.warehouse_type
    ADD CONSTRAINT warehouse_type_pkey PRIMARY KEY (id);

ALTER TABLE ONLY depot.warehouse_us
    ADD CONSTRAINT warehouse_us_pkey PRIMARY KEY (warehouse_address_id);

ALTER TABLE ONLY shipping.package_status
    ADD CONSTRAINT package_status_code_unique UNIQUE (code);

ALTER TABLE ONLY shipping.package_status
    ADD CONSTRAINT package_status_displayname_unique UNIQUE (display_name);

ALTER TABLE ONLY shipping.package_status
    ADD CONSTRAINT package_status_pkey PRIMARY KEY (id);

ALTER TABLE ONLY shipping.tempo_package
    ADD CONSTRAINT tempo_package_pkey PRIMARY KEY (id);

ALTER TABLE ONLY shipping.tempo_package
    ADD CONSTRAINT tempo_package_trackingnumber_unique UNIQUE (tracking_number);

-- ─────────────────────────────────────────────────────────────────────────────
-- ÍNDICES (BTREE)
-- ─────────────────────────────────────────────────────────────────────────────
CREATE INDEX fk_role_user_role_idx ON auth.tempo_role_user USING btree (role_id);
CREATE INDEX fk_role_user_user_idx ON auth.tempo_role_user USING btree (user_id);
CREATE INDEX fk_session_user_idx ON auth.session USING btree (user_id);
CREATE INDEX fk_user_client_idx ON auth.tempo_user USING btree (client_id);

CREATE INDEX fk_business_client_idx ON client.business USING btree (client_id);
CREATE INDEX fk_client_client_idx ON client.client USING btree (referred_by_client_id);
CREATE INDEX fk_client_client_type_idx ON client.client USING btree (type_id);
CREATE INDEX fk_delivery_address_client_idx ON client.delivery_address USING btree (client_id);
CREATE INDEX fk_individual_client_idx ON client.individual USING btree (client_id);
CREATE INDEX fk_individual_identity_type_idx ON client.individual USING btree (identity_type_id);

CREATE INDEX fk_warehouse_address_warehouse_type_idx ON depot.warehouse_address USING btree (warehouse_type_id);
CREATE INDEX fk_warehouse_cn_warehouse_address_idx ON depot.warehouse_cn USING btree (warehouse_address_id);
CREATE INDEX fk_warehouse_co_warehouse_address_idx ON depot.warehouse_co USING btree (warehouse_address_id);
CREATE INDEX fk_warehouse_us_warehouse_address_idx ON depot.warehouse_us USING btree (warehouse_address_id);

CREATE INDEX fk_tempo_package_client_idx ON shipping.tempo_package USING btree (client_id);
CREATE INDEX fk_tempo_package_delivery_address_idx ON shipping.tempo_package USING btree (delivery_address_id);
CREATE INDEX fk_tempo_package_package_status_idx ON shipping.tempo_package USING btree (package_status_id);
CREATE INDEX fk_tempo_package_warehouse_address_idx ON shipping.tempo_package USING btree (warehouse_address_id);

-- ─────────────────────────────────────────────────────────────────────────────
-- FOREIGN KEYS
-- ─────────────────────────────────────────────────────────────────────────────
ALTER TABLE ONLY auth.tempo_role_user
    ADD CONSTRAINT fk_role_user_role FOREIGN KEY (role_id) REFERENCES auth.tempo_role(id) ON DELETE CASCADE;

ALTER TABLE ONLY auth.tempo_role_user
    ADD CONSTRAINT fk_role_user_user FOREIGN KEY (user_id) REFERENCES auth.tempo_user(id) ON DELETE CASCADE;

ALTER TABLE ONLY auth.session
    ADD CONSTRAINT fk_session_user FOREIGN KEY (user_id) REFERENCES auth.tempo_user(id) ON DELETE CASCADE;

ALTER TABLE ONLY auth.tempo_user
    ADD CONSTRAINT fk_tempo_user_client FOREIGN KEY (client_id) REFERENCES client.client(id);

ALTER TABLE ONLY client.business
    ADD CONSTRAINT fk_business_client FOREIGN KEY (client_id) REFERENCES client.client(id);

ALTER TABLE ONLY client.client
    ADD CONSTRAINT fk_client_client FOREIGN KEY (referred_by_client_id) REFERENCES client.client(id);

ALTER TABLE ONLY client.client
    ADD CONSTRAINT fk_client_client_type FOREIGN KEY (type_id) REFERENCES client.client_type(id);

ALTER TABLE ONLY client.delivery_address
    ADD CONSTRAINT fk_delivery_address_client FOREIGN KEY (client_id) REFERENCES client.client(id);

ALTER TABLE ONLY client.individual
    ADD CONSTRAINT fk_individual_client FOREIGN KEY (client_id) REFERENCES client.client(id);

ALTER TABLE ONLY client.individual
    ADD CONSTRAINT fk_individual_identity_type FOREIGN KEY (identity_type_id) REFERENCES client.identity_type(id);

ALTER TABLE ONLY depot.warehouse_address
    ADD CONSTRAINT fk_warehouse_address_warehouse_type FOREIGN KEY (warehouse_type_id) REFERENCES depot.warehouse_type(id);

ALTER TABLE ONLY depot.warehouse_cn
    ADD CONSTRAINT fk_warehouse_cn_warehouse_address FOREIGN KEY (warehouse_address_id) REFERENCES depot.warehouse_address(id);

ALTER TABLE ONLY depot.warehouse_co
    ADD CONSTRAINT fk_warehouse_cn_warehouse_address FOREIGN KEY (warehouse_address_id) REFERENCES depot.warehouse_address(id);

ALTER TABLE ONLY depot.warehouse_us
    ADD CONSTRAINT fk_warehouse_us_warehouse_address FOREIGN KEY (warehouse_address_id) REFERENCES depot.warehouse_address(id);

ALTER TABLE ONLY shipping.tempo_package
    ADD CONSTRAINT fk_tempo_package_client FOREIGN KEY (client_id) REFERENCES client.client(id);

ALTER TABLE ONLY shipping.tempo_package
    ADD CONSTRAINT fk_tempo_package_delivery_address FOREIGN KEY (delivery_address_id) REFERENCES client.delivery_address(id);

ALTER TABLE ONLY shipping.tempo_package
    ADD CONSTRAINT fk_tempo_package_package_status FOREIGN KEY (package_status_id) REFERENCES shipping.package_status(id);

ALTER TABLE ONLY shipping.tempo_package
    ADD CONSTRAINT fk_tempo_package_warehouse_address FOREIGN KEY (warehouse_address_id) REFERENCES depot.warehouse_address(id);

-- CREATE POBOX SEQUENCE
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_class c
    JOIN pg_namespace n ON n.oid = c.relnamespace
    WHERE c.relkind = 'S' AND c.relname = 'po_box_seq' AND n.nspname = 'client'
  ) THEN
    CREATE SEQUENCE client.po_box_seq
      START WITH 3000
      INCREMENT BY 1
      NO MINVALUE
      NO MAXVALUE
      CACHE 1;
  END IF;
END$$;

-- 2. Si ya hay datos, poner la secuencia en el valor correcto:
--    nextval() debe devolver MAX(po_box_number) + 1
SELECT setval('client.po_box_seq', GREATEST(COALESCE((SELECT MAX(po_box_number) FROM client.client), 0), 2999));

-- 3. Asociar la secuencia a la columna y establecer DEFAULT
ALTER SEQUENCE client.po_box_seq OWNED BY client.client.po_box_number;
ALTER TABLE client.client ALTER COLUMN po_box_number SET DEFAULT nextval('client.po_box_seq');

-- ============================================================================
-- Fin de V1__init.sql
-- ============================================================================